### ISSUE TITLE
Empty Avro File

### ISSUE THREAD

**Issue by blakesha** [martijns/AvroViewer#2]
If the content of the avro file is empty the application is throwing the following error:

appname: AvroViewer
appversion: 1.0.0.65
errormessage: Specified argument was out of the range of valid values.
Parameter name: size
fullexception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: size
   at Microsoft.Hadoop.Avro.BinaryDecoder.DecodeFixed(Int32 size)
   at Microsoft.Hadoop.Avro.Container.StreamReader`1.MoveNext()
   at AvroViewerGui.MainForm.GetEntities(String filename)
   at AvroViewerGui.MainForm.<>c__DisplayClass22_0.<LoadFromFile>b__0()
   at MsCommon.ClickOnce.AppForm.<>c__DisplayClass10_0.<PerformWork>b__0()

**Comment by kipusoep** [comment]
Ran into the same issue.
